### ISSUE TITLE
README.md: missing CiviRules screenshot

### ISSUE THREAD

**Issue by kenwest** [veda-consulting-company/ncn-civi-zoom#18]
README.md says "Once you've decided this you can create a new CiviRule as per the screen shot" but there is no screenshot.

- I assume the trigger is "Event Participant is added"
- I assume the conditions should include a Field Value Comparison that the Event's Zoom Account Id 
is not empty
- the actions should include "Add Participant to Zoom"

**Comment by veda-consulting** [comment]
This has been resolved with PR #21
