### ISSUE TITLE
Documentation to be added to Readme perhaps

### ISSUE THREAD

**Issue by petednz** [veda-consulting-company/ncn-civi-zoom#9]
Trying to start the ball rolling here. This is where I got to

### CiviCRM Custom fields

In CiviCRM create your Custom Field(s) for Events for Webinar / Meeting ID

### Zoom API keys etc

Sign in to marketplace.zoom.us with the Zoom account in question go to /develop/create and choose JWT

Fill in required fields

Copy API key and Secret and add to Civi settings (use the copy link to avoid copying 'copy' on end of API Key)

Base url should be https://api.zoom.us/v2

### Create CiviRule
Select trigger of Add Participant 
Select Action of Add Participant to Zoon

### Create Zoom webinar / Meeting

If it is a Webinar then set it to be enabled for registration!

Copy Webinar / Meeting ID

### CIviZoom settings

Paste Webinar / Meeting ID (I assume without the spaces but perhaps with and without both work) to /civicrm/Zoom/settings?reset=1 

Add your Custom Fields to the settings.

### Testing if it is all working
Register a Participant

Run the civirules scheduled Job

Login to Zoom  and visit the Meeting or Webinar page and you should see the number of participants near bottom of screen (Look for "Manage Attendees: Registrants")

Or go to Account Management > Reports

**Comment by veda-consulting** [comment]
Hey @petednz we had a PR outstanding that had multiple README updates. Maybe you want to review what we have and see if it meets your expectations?

**Comment by petednz** [comment]
I must be looking in wrong place. I saw this but it was only a minor change
https://github.com/krd-consulting/ncn-civi-zoom/pull/3/commits/81f7c5998e8c3cefe448264fe2caaf2136fc6030
will keep looking

**Comment by petednz** [comment]
I had a read of https://github.com/krd-consulting/ncn-civi-zoom/pull/3/files?short_path=04c6e90#diff-04c6e90faac2675aa89e2176d2eec7d8 and my sense is it does not follow the logic flow of ensuring users set up the things they need in the right order rather than following the steps only to figure they have to jump back and do something prior to being able to complete that step eg 
- you need some civi custom fields before you can usefully complete the civi Zoom settings
also some basic 'how to navigate Zoom' would be useful to a first timer hence including those steps in my documentation to help step a person through everything assuming they are unfamiliar with the whole setup.

**Comment by veda-consulting** [comment]
@petednz yeah, we're planning on doing a civicrm.tv thing on it this week, hopefully that'll fill in any gaps

**Comment by petednz** [comment]
sounds good, but a lot of folk will still just go through the readme step by step and imo what i have pasted above is much more likely help folk follow step by step - but perhaps you can test that out while prepping for the tv slot :-)

**Comment by veda-consulting** [comment]
@petednz I've updated the documentation and our install video is here https://youtu.be/6rta9V3J7yc

Take a look and let me know how you get on, closing this for now
